image: Ubuntu2004

services:
- docker

build:
-  docker build --tag travis-ubuntu20.04 --build-arg JOB_NUMBER=1 --build-arg BRANCH="master" --build-arg USE_TENSORFLOW="true" -f ./continuous_integration/Dockerfile-travis-ubuntu20.04 .

test_script:
- echo "Test script" 

on_success:
- echo "Success"

on_failure:
- echo "Failure"
