configuration: Release

environment:
  matrix:
  - job_name: Visual Studio 2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - job_name: Ubuntu 20.04
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004

for:
  - matrix:
      only:
        - job_name: Ubuntu 20.04
    services:
      - docker
    build_script:
      - docker build --tag travis-ubuntu20.04 --build-arg JOB_NUMBER=1 --build-arg BRANCH="master" --build-arg USE_TENSORFLOW="true" -f ./continuous_integration/Dockerfile-travis-ubuntu20.04 .
  - matrix:
      only:
        - job_name: Visual Studio 2017
    environment:
      LIMA_DIST: c:\d
      LIMA_EXTERNALS: c:/d
      LIMA_CONF: 'c:\b\execEnv\config'
      LIMA_RESOURCES: 'c:\b\execEnv\resources'
      #Qt5_INSTALL_DIR: 'C:\Qt\5.15.0\msvc2019_64'
      Qt5_INSTALL_DIR: 'C:\Qt\5.13.2\msvc2017_64'
      #BOOST_ROOT: 'C:\Libraries\boost_1_71_0'
      BOOST_ROOT: 'C:\Libraries\boost_1_69_0'
      #BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_71_0\lib64-msvc-14.2'
      BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_69_0\lib64-msvc-14.1'
      LIMA_DISABLE_FSW_TESTING: true
      NLTK_PTB_DP_DIR: 'c:\dependency_treebank'
      NLTK_PTB_DP_FILE: 'c:\dependency_treebank\nltk-ptb.dp'
      GITHUB_OAUTH_TOKEN:
        secure: 01sh5OxKgkUJbTt/ldX/duLQk6iP28Iwet3reW8FK8f7Z3xiM2RLHQUwOzZye4qs
      PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      PATH: "%PYTHON%;%PYTHON%\\libs;c:\\b\\execEnv\\lib;%Qt5_INSTALL_DIR%\\bin;%BOOST_LIBRARYDIR%;c:\\msys64\\usr\\bin;%PATH%"

    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    on_failure:
      - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    install:
      - ps: Install-Module Pscx -Scope CurrentUser -AllowClobber
      - ps: (new-object net.webclient).DownloadFile('http://www.nltk.org/nltk_data/packages/corpora/dependency_treebank.zip', 'c:\dependency_treebank.zip')
      - ps: Invoke-BatchFile "c:\\projects\\lima\\continuous_integration\\appveyor_win_install.bat"
      - ps: "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12"
      - ps: (New-Object System.Net.WebClient).DownloadFile("https://github.com/aymara/qhttpserver/releases/download/20180703132951-64591f4d/qhttpserver-0.0.20180703132951-64591f4d-win64.exe","c:/projects/lima/qhttpserver.exe")

    build_script:
      - ps: $env:LIMA_VERSION_RELEASE="$(git log --date=iso  -1 | grep Date | grep -Po "[1-9]\d{3}\-[0-1]\d-[0-3]\d +[0-2]\d:[0-6]\d:[0-6]\d" | sed -e 's/\+.*//' -e 's/[- :]//g')-$(git log --format=%h --abbrev=8 -1)"
      - ps: echo $env:LIMA_VERSION_RELEASE
      - ps: Invoke-BatchFile "c:\\projects\\lima\\continuous_integration\\appveyor_win_build.bat"

    after_build:
      - ps: Invoke-BatchFile "c:\\projects\\lima\\continuous_integration\\appveyor_win_after_build.bat" $env:APPVEYOR_BUILD_FOLDER

    artifacts:
      - path: lima*.exe
        name: packages

    deploy:
      description: '$(LIMA_VERSION_RELEASE)'
      provider: GitHub
      tag: $(LIMA_VERSION_RELEASE)
      auth_token:
        secure: 01sh5OxKgkUJbTt/ldX/duLQk6iP28Iwet3reW8FK8f7Z3xiM2RLHQUwOzZye4qs
      artifact: packages
      force_update: true
      on:
        branch: master                 # release from master branch only
        APPVEYOR_REPO_TAG: false       # deploy on non tag push only

